# Generated by Django 5.0.6 on 2024-11-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_pictures/'),
        ),
    ]
