# Generated by Django 5.0.6 on 2024-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_mesurment_ingredient_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('cup', 'Cup'), ('g', 'Gram'), ('tbs', 'Tablespoon'), ('tsp', 'Teaspoon'), ('ml', 'Milliliter'), ('l', 'Liter'), ('lbs', 'Pound'), ('b', 'Bag'), ('p', 'Piece(s)')], max_length=50, null=True),
        ),
    ]
