# Generated by Django 5.0.6 on 2025-01-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('cup', 'Cup'), ('gram', 'Gram'), ('tbs', 'Tablespoon'), ('tsp', 'Teaspoon'), ('ml', 'Milliliter'), ('liter', 'Liter'), ('lbs', 'Pound'), ('bag', 'Bag'), ('piece(s)', 'Piece(s)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
