# Generated by Django 5.0.6 on 2025-01-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('cup', 'Cup'), ('gram', 'Gram'), ('tbs', 'Tablespoon'), ('tsp', 'Teaspoon'), ('Milliliter', 'Milliliter'), ('liter', 'Liter'), ('Pound', 'Pound'), ('bag', 'Bag'), ('piece(s)', 'Piece(s)'), ('slice(s)', 'Slices')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
