# Generated by Django 5.0.6 on 2025-01-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_ingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
