# Generated by Django 5.0.6 on 2025-02-11 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_subrecipe': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_subrecipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('cup', 'Cup'), ('gram', 'Gram'), ('tbs', 'Tablespoon'), ('tsp', 'Teaspoon'), ('Milliliter', 'Milliliter'), ('liter', 'Liter'), ('Pound', 'Pound'), ('bag', 'Bag'), ('piece(s)', 'Piece(s)'), ('slice(s)', 'Slices')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
