# Generated by Django 5.0.6 on 2025-02-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_ingredient_sub_recipe_recipe_is_subrecipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_subrecipe': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_recipe', to='recipes.recipe'),
        ),
    ]
