# Generated by Django 5.0.6 on 2025-02-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_ingredient_sub_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSubRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_notes', models.TextField(blank=True, null=True)),
                ('sub_recipe_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_recipe_measurement', models.CharField(blank=True, choices=[('cup', 'Cup'), ('gram', 'Gram'), ('tbs', 'Tablespoon'), ('tsp', 'Teaspoon'), ('Milliliter', 'Milliliter'), ('liter', 'Liter'), ('Pound', 'Pound'), ('bag', 'Bag'), ('piece(s)', 'Piece(s)'), ('slice(s)', 'Slices')], max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mesurment',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='sub_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipesubrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_recipe', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipesubrecipe',
            name='sub_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_sub_recipes', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='related_sub_recipes',
            field=models.ManyToManyField(related_name='sub_recipes', through='recipes.RecipeSubRecipe', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipesubrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'sub_recipe'), name='unique_parent_child_relation'),
        ),
    ]
