# Generated by Django 5.0.6 on 2025-02-25 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_recipe_is_subrecipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ingredients', to='recipes.subrecipe'),
        ),
        migrations.AddField(
            model_name='step',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_steps', to='recipes.subrecipe'),
        ),
    ]
