# Generated by Django 5.0.6 on 2025-03-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_remove_step_recipe_remove_step_sub_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrecipe',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_recipe',
            field=models.ManyToManyField(related_name='main_recipes', through='recipes.RecipeSubRecipe', to='recipes.subrecipe'),
        ),
    ]
