# Generated by Django 5.0.6 on 2025-03-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_remove_subrecipe_recipes_recipe_sub_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='sub_recipe',
            field=models.ManyToManyField(blank=True, null=True, related_name='main_recipes', through='recipes.RecipeSubRecipe', to='recipes.subrecipe'),
        ),
    ]
