# Generated by Django 5.0.6 on 2025-03-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_alter_recipe_sub_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='sub_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_recipes',
            field=models.ManyToManyField(blank=True, related_name='main_recipes', through='recipes.RecipeSubRecipe', to='recipes.subrecipe'),
        ),
    ]
