# Generated by Django 5.0.6 on 2025-03-18 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_remove_recipe_sub_recipe_recipe_sub_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrecipeingredient',
            name='sub_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_ingredients', to='recipes.subrecipe'),
        ),
    ]
