# Generated by Django 5.0.6 on 2025-03-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_alter_subrecipeingredient_sub_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesubrecipe',
            name='specific_notes',
        ),
        migrations.RemoveField(
            model_name='recipesubrecipe',
            name='sub_recipe_measurement',
        ),
        migrations.RemoveField(
            model_name='recipesubrecipe',
            name='sub_recipe_quantity',
        ),
    ]
