# Generated by Django 5.0.6 on 2025-05-06 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_remove_recipesubrecipe_specific_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('cup', 'Cup'), ('gram', 'Gram'), ('tbs', 'Tablespoon'), ('tsp', 'Teaspoon'), ('milliliter', 'Milliliter'), ('liter', 'Liter'), ('pound', 'Pound'), ('bag', 'Bag'), ('piece(s)', 'Piece(s)'), ('slice(s)', 'Slices')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subrecipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('cup', 'Cup'), ('gram', 'Gram'), ('tbs', 'Tablespoon'), ('tsp', 'Teaspoon'), ('milliliter', 'Milliliter'), ('liter', 'Liter'), ('pound', 'Pound'), ('bag', 'Bag'), ('piece(s)', 'Piece(s)'), ('slice(s)', 'Slices')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='recipes.category')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(related_name='recipes', to='recipes.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_parent_to_sub_categories_relation'),
        ),
    ]
