# Generated by Django 5.0.6 on 2025-06-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
