# Generated by Django 5.0.6 on 2025-06-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
    ]
