# Generated by Django 5.0.6 on 2025-07-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_remove_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_pictures_originals/'),
        ),
    ]
