# Generated by Django 5.0.6 on 2025-07-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_recipe_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
    ]
