# Generated by Django 5.0.6 on 2025-07-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0040_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_pictures_originals/'),
        ),
    ]
