# Generated by Django 5.0.6 on 2025-10-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0043_alter_category_name_alter_recipe_title_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipesubrecipe',
            name='unique_parent_child_relation',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='sub_recipes',
        ),
        migrations.RemoveField(
            model_name='recipesubrecipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_sub_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='parent_recipe',
            field=models.ManyToManyField(blank=True, related_name='sub_recipe', through='recipes.RecipeSubRecipe', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipesubrecipe',
            name='parent_recipe',
            field=models.ForeignKey(blank=True, default=None,null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_recipe_relation', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipesubrecipe',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_recipe_relation', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipesubrecipe',
            constraint=models.UniqueConstraint(fields=('parent_recipe', 'sub_recipe'), name='unique_parent_child_relation'),
        ),
    ]
