# Generated by Django 5.0.6 on 2025-10-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0044_remove_recipesubrecipe_unique_parent_child_relation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipesubrecipe',
            name='unique_parent_child_relation',
        ),
        migrations.AlterField(
            model_name='recipesubrecipe',
            name='parent_recipe',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parent_recipe_relation', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipesubrecipe',
            constraint=models.UniqueConstraint(fields=('parent_recipe', 'sub_recipe'), name='recipes_recipesubrecipe_unique_parent_child_relation'),
        ),
        migrations.AddConstraint(
            model_name='recipesubrecipe',
            constraint=models.CheckConstraint(check=models.Q(('parent_recipe', models.F('sub_recipe')), _negated=True), name='recipes_recipesubrecipe_no_self_reference'),
        ),
    ]
