# Generated by Django 5.0.6 on 2025-10-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0045_remove_recipesubrecipe_unique_parent_child_relation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrecipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subrecipestep',
            name='sub_recipe',
        ),
        migrations.DeleteModel(
            name='SubRecipeIngredient',
        ),
        migrations.DeleteModel(
            name='SubRecipe',
        ),
        migrations.DeleteModel(
            name='SubRecipeStep',
        ),
    ]
